export const SHOW_LOADER = "APP/SHOW_LOADER";
export const HIDE_LOADER = "APP/HIDE_LOADER";
export const ADD_LIST_ITEM = "APP/LIST/ADD_CONTENT";
export const REMOVE_LIST_ITEM = "APP/LIST/REMOVE_CONTENT";
export const UP_LIST_ITEM = "APP/LIST/UP_LIST_ITEM";
export const DOWN_LIST_ITEM = "APP/LIST/DOWN_LIST_ITEM";
